Update smr.yml

diff --git a/.github/workflows/smr.yml b/.github/workflows/smr.yml
--- a/.github/workflows/smr.yml
+++ b/.github/workflows/smr.yml
@@ -90,34 +90,34 @@ jobs:
           # PATCH="${VERSION_PARTS[2]}"
           
           # # Calculate the expected version based on bump level
-          # if [ "$BUMP_LEVEL" == "minor" ] && [ -n "$INPUT_VERSION" ]; then
-          #     # EXPECTED_VERSION="$MAJOR.$((MINOR + 1)).$PATCH"
-          #     EXPECTED_VERSION=$(node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))")
-          # elif [ "$BUMP_LEVEL" == "patch" ] && [ -n "$INPUT_VERSION" ]; then
-          #     # EXPECTED_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
-          #     EXPECTED_VERSION=$(node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))")
-          # fi
+          if [ "$BUMP_LEVEL" == "minor" ] && [ -n "$INPUT_VERSION" ]; then
+              # EXPECTED_VERSION="$MAJOR.$((MINOR + 1)).$PATCH"
+              EXPECTED_VERSION=$(node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))")
+          elif [ "$BUMP_LEVEL" == "patch" ] && [ -n "$INPUT_VERSION" ]; then
+              # EXPECTED_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
+              EXPECTED_VERSION=$(node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))")
+          fi
           
           # echo "EXPECTED version is ${EXPECTED_VERSION}"
           
           # # ######## Update and create tag of semantic version ########
           
           # # Check if bumpLevel and input are specified
-          # if [ -n "$BUMP_LEVEL" ] && [ -n "$INPUT_VERSION" ]; then
-          #     # For non-semver bumps, compare with the expected version
-          #     if [ "$BUMP_LEVEL" != "semver" ]; then
-          #         if [ "$INPUT_VERSION" == "$EXPECTED_VERSION" ]; then
-          #             # Check if bumplevel is minor/patch and Input version matches with expected output,Create a tag and push to branch.
-          #             echo "Creating tag for specified version ($INPUT_VERSION)..."
-          #             npm version $EXPECTED_VERSION
-          #             # git tag -a "$INPUT_VERSION" -m "Release Version"
-          #             # git push origin main --follow-tags
-          #         else
-          #             echo "Error: Specified bump-level ($BUMP_LEVEL) does not match expected version ($EXPECTED_VERSION). CI fails because instructions are unclear"
-          #             exit 1  # Exit with an error code
-          #         fi
-          #     fi
-          # fi
+          if [ -n "$BUMP_LEVEL" ] && [ -n "$INPUT_VERSION" ]; then
+              # For non-semver bumps, compare with the expected version
+              if [ "$BUMP_LEVEL" != "semver" ]; then
+                  if [ "$INPUT_VERSION" == "$EXPECTED_VERSION" ]; then
+                      # Check if bumplevel is minor/patch and Input version matches with expected output,Create a tag and push to branch.
+                      echo "Creating tag for specified version ($INPUT_VERSION)..."
+                      npm version $EXPECTED_VERSION
+                      # git tag -a "$INPUT_VERSION" -m "Release Version"
+                      git push origin main --follow-tags
+                  else
+                      echo "Error: Specified bump-level ($BUMP_LEVEL) does not match expected version ($EXPECTED_VERSION). CI fails because instructions are unclear"
+                      exit 1  # Exit with an error code
+                  fi
+              fi
+          fi
           
           # Use the specified version and bump level to input version
           if [ "$BUMP_LEVEL" == "semver" ]; then
@@ -130,28 +130,29 @@ jobs:
               git status
               npm version $INPUT_VERSION -m "test"
               git push origin main --follow-tags
-              
           fi
                          
           # Check if bumpLevel is minor/patch AND semver is empty, then use it for bumping
-          # if [[ "${BUMP_LEVEL}" == "minor" || "${BUMP_LEVEL}" == "patch" ]] && [ -z "$INPUT_VERSION" ]; then
-          #     echo "Using default bump level for versioning."
+          if [[ "${BUMP_LEVEL}" == "minor" || "${BUMP_LEVEL}" == "patch" ]] && [ -z "$INPUT_VERSION" ]; then
+              echo "Using default bump level for versioning."
           
-          #     # Perform version bumping using npm
-          #     if [ "${BUMP_LEVEL}" == "minor" ]; then
-          #         echo "Bumping version with 'minor' level."
-          #         npm --no-git-tag-version version minor
-          #     elif [ "${BUMP_LEVEL}" == "patch" ]; then
-          #         echo "Bumping version with 'patch' level."
-          #         npm --no-git-tag-version version patch
-          #     fi
+              # Perform version bumping using npm
+              if [ "${BUMP_LEVEL}" == "minor" ]; then
+                  echo "Bumping version with 'minor' level."
+                  node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))"
+                  # npm --no-git-tag-version version minor
+              elif [ "${BUMP_LEVEL}" == "patch" ]; then
+                  echo "Bumping version with 'patch' level."
+                  node -e "console.log(require('semver').inc('$CURRENT_VERSION', '$BUMP_LEVEL'))"
+                  # npm --no-git-tag-version version patch
+              fi
           
-          #     COMMIT_TAG="$(node -p "require('./package.json').version")"
-          #     echo "COMMIT_TAG=${COMMIT_TAG}" >>$GITHUB_ENV
+              COMMIT_TAG="$(node -p "require('./package.json').version")"
+              echo "COMMIT_TAG=${COMMIT_TAG}" >>$GITHUB_ENV
               
-          #     git add package.json package-lock.json
-          #     git commit -m "Bump version to ${COMMIT_TAG}"
-          #     git tag -a "${COMMIT_TAG}" -m "Release Version"
-          #     git push origin main --follow-tags
-          # fi
+              git add package.json package-lock.json
+              git commit -m "Bump version to ${COMMIT_TAG}"
+              git tag -a "${COMMIT_TAG}" -m "Release Version"
+              git push origin main --follow-tags
+          fi
           
